'use strict';

const obviousSpam = [
  'Hello California Handyman, not having online booking means you miss out on easy jobs. I can add a booking system to your site.',
  'Not having a booking system means lost jobs. I can install one for you.',
  'Not having online booking costs you customers. Would you be interested?',
  'I help businesses get more bookings with automated scheduling.',
  'I help local businesses improve SEO and attract customers.',
  'Would you be interested in a new booking platform for your company?',
  'Would you be interested in improving your Google rankings?',
  'Can I send you a proposal for a booking system?',
  'Can I send a free SEO report for your website?',
  'We build websites for contractors. Can I send examples?',
  'I create marketing campaigns that generate qualified leads.',
  'Need more leads? We can help your handyman company.',
  'Get more customers with our local search service.',
  'Your competitors rank higher. Let us fix that.',
  'I noticed your site could convert more visitors into jobs.',
  'We offer appointment scheduling software for service businesses.',
  'I can add appointment scheduling to your site.',
  'I can build a scheduling system for your website.',
  'We can create an online scheduler for customers.',
  'Our agency specializes in contractor websites and advertising.',
  'Book a quick call to discuss growing your customer base.',
  'FREE website audit — interested?',
  'Complimentary SEO analysis available at https://agency.example/audit',
  'See our lead packages: www.growth.example',
  'We guarantee 20 handyman leads per month.',
  'Pay per lead marketing for home-service companies.',
  'I would like to redesign your website.',
  'We would like to improve your search visibility.',
  'Can we handle your social ads?',
  'Your business needs a better web-site.',
  'I can design your web site to win more work.',
  'I can improve your Google Business Profile.',
  'I can optimize your site for local search.',
  'I can generate leads for your handyman service.',
  'I can get your company onto page one of Google.',
  'I help businesses\nget found on Google\nand book more jobs.',
  'WOULD YOU BE INTERESTED IN MORE LEADS?',
  'cAn I sEnD yOu OuR mArKeTiNg PaCkAgEs?',
  'N O T  H A V I N G  O N L I N E  B O O K I N G loses jobs.',
  'I can add a booking-system to your site.',
  'I can add an online-booking system to your website.',
  'I can help you with lead-generation.',
  'We can improve your S.E.O.',
  'We can improve your S E O.',
  'We can improve your S‑E‑O.',
  'We can improve your SEО.',
  'We can improve your SЕO.',
  'We can improve your SＥＯ.',
  'We can improve your S\u200bEO.',
  'I can add a booking\u200b system to your site.',
  'I can add a bοoking system to your site.',
  'I can add online bоoking to your site.',
  'I can build your webѕite.',
  'I can improve your digital\u200cmarketing.',
  'Lead\u200bgeneration for contractors — interested?',
  'hxxps://growth.example — handyman customer acquisition services.',
  'growth.example/seo — can I send pricing?',
  'calendly.com/agency/demo Let’s discuss more customers.',
  'I help businesses with appointment automation; can I send details',
  'More customers for your handyman business — reply for pricing.',
  'SEO services for contractors. Reply if interested.',
  'Website redesign for your handyman company — can I send examples?',
  'Lead gen for handymen. Book a quick call.',
  'Marketing partnership to grow your business. Interested?',
];

const legitimateLeads = [
  'The bedroom door sticks and needs repair. Can you provide an estimate?',
  'Can I send photos of the broken door?',
  'Would you be interested in quoting a fence repair?',
  'Do you have online booking? I am trying to schedule a repair.',
  'Your booking system did not let me choose a time. I need a shelf mounted.',
  'I help businesses maintain rental properties and need three doors repaired.',
  'Our marketing office needs shelves installed.',
  'The website says you offer general repairs; can I get an estimate?',
  'Not having a working gate is a safety issue. Please repair it.',
  'Can you repair the sign at my lead generation office?',
  'SEO agency tenant here; we need a door repaired.',
  'I can help you with SEO if needed, but today I need you to repair my backyard gate.',
  'We can improve your website later; right now please install shelves in our Valencia office.',
  'I would like to set up digital marketing displays after you mount the TV brackets.',
  'We could build a website for you, but this request is to fix our office door closer.',
  'I can set up a booking system tablet after you mount it securely beside the salon counter.',
  'We can add a booking system tablet to reception if you install the wall bracket and outlet cover.',
  'We can improve your website design studio by adding built-in shelving along the back wall.',
  'I would like to create a website filming corner; please mount backdrop hooks and shelves.',
  'Our digital marketing agency wants more customers, plus we need shelving installed in supply room.',
  'Online booking is how my salon works and we miss out on appointments when the tablet falls; please mount it.',
  'We would like to help you with digital marketing someday; today can you install our office sign?',
  'I can improve SEO, but my handyman request is to anchor a cabinet to the wall.',
  'I own a digital marketing business and we can improve our office by adding built-in shelving; reference photos: https://example.com/shelves',
  'I can help set up a new desk in my digital marketing home office.',
  'Photos of the broken cabinet are at https://photos.example/album.',
  'Please install a wall tablet that our customers use for online booking.',
  'Our website filming room needs curtain rods and backdrop hooks installed.',
  'The Google Business Profile sign fell from the wall; can you remount it?',
  'Need help assembling a desk for our social media manager.',
  'Can you improve the shelving in our lead generation office?',
  'Please set up this IKEA cabinet and anchor it safely.',
  'The booking software kiosk needs a physical wall bracket installed.',
  'Our contractor website office has a damaged baseboard that needs repair.',
  'I miss out on using the room because the door will not close. Please fix it.',
  'Can I send a product link for the faucet you would install?',
  'Would you be interested in helping with drywall repair next Tuesday?',
  'We need more storage. Can you build simple shelves in the garage?',
  'I would like to improve our home office by mounting two monitors.',
];

module.exports = { obviousSpam, legitimateLeads };
